$axure.loadCurrentPage({
  "url":"loading.html",
  "generationDate":new Date(1460297997880.07),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1823d4efbdf04ab1996b4c39ba6125f1",
    "type":"Axure:Page",
    "name":"loading",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"用例 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"fadeWidget",
                "description":"显示 1 向右滑动 500 ms,<br>0",
                "objectsToFades":[{
                    "objectPath":["e3073c2586f8492ab3c0cbe2575e1916"],
                    "fadeInfo":{
                      "fadeType":"show",
                      "options":{
                        "easing":"slideRight",
                        "duration":500,
                        "showType":"none"}}},
{
                    "objectPath":["83496704048444b784de9b3eef4aae98"],
                    "fadeInfo":{
                      "fadeType":"show",
                      "options":{
                        "showType":"none"}}}]},
{
                "action":"wait",
                "description":"等待1000毫秒",
                "waitTime":1000},
{
                "action":"fadeWidget",
                "description":"隐藏 0",
                "objectsToFades":[{
                    "objectPath":["83496704048444b784de9b3eef4aae98"],
                    "fadeInfo":{
                      "fadeType":"hide",
                      "options":{
                        "showType":"none"}}}]},
{
                "action":"fadeWidget",
                "description":"显示 25 向右滑动 500 ms,<br>20",
                "objectsToFades":[{
                    "objectPath":["d1ed500786c44acd8f0523c752a3a3b9"],
                    "fadeInfo":{
                      "fadeType":"show",
                      "options":{
                        "easing":"slideRight",
                        "duration":500,
                        "showType":"none"}}},
{
                    "objectPath":["021f2d64b29c46c19093b6c8bcecafe6"],
                    "fadeInfo":{
                      "fadeType":"show",
                      "options":{
                        "showType":"none"}}}]},
{
                "action":"wait",
                "description":"等待1000毫秒",
                "waitTime":1000},
{
                "action":"fadeWidget",
                "description":"隐藏 20",
                "objectsToFades":[{
                    "objectPath":["021f2d64b29c46c19093b6c8bcecafe6"],
                    "fadeInfo":{
                      "fadeType":"hide",
                      "options":{
                        "showType":"none"}}}]},
{
                "action":"fadeWidget",
                "description":"显示 50 向右滑动 500 ms,<br>50",
                "objectsToFades":[{
                    "objectPath":["575611b2585f43a1aed9677af23c3c85"],
                    "fadeInfo":{
                      "fadeType":"show",
                      "options":{
                        "easing":"slideRight",
                        "duration":500,
                        "showType":"none"}}},
{
                    "objectPath":["e4edf30b18e04564b837055c70551f9e"],
                    "fadeInfo":{
                      "fadeType":"show",
                      "options":{
                        "showType":"none"}}}]},
{
                "action":"wait",
                "description":"等待1000毫秒",
                "waitTime":1000},
{
                "action":"fadeWidget",
                "description":"隐藏 50",
                "objectsToFades":[{
                    "objectPath":["e4edf30b18e04564b837055c70551f9e"],
                    "fadeInfo":{
                      "fadeType":"hide",
                      "options":{
                        "showType":"none"}}}]},
{
                "action":"fadeWidget",
                "description":"显示 75 向右滑动 500 ms,<br>75",
                "objectsToFades":[{
                    "objectPath":["2ce8578607bd4c718550b6ab40b95fa8"],
                    "fadeInfo":{
                      "fadeType":"show",
                      "options":{
                        "easing":"slideRight",
                        "duration":500,
                        "showType":"none"}}},
{
                    "objectPath":["803f028e51c44421bcea4d7b6fe2187f"],
                    "fadeInfo":{
                      "fadeType":"show",
                      "options":{
                        "showType":"none"}}}]},
{
                "action":"wait",
                "description":"等待1000毫秒",
                "waitTime":1000},
{
                "action":"fadeWidget",
                "description":"显示 100 向右滑动 500 ms,<br>100",
                "objectsToFades":[{
                    "objectPath":["37a1a6faf7894112a3a893d8b03164de"],
                    "fadeInfo":{
                      "fadeType":"show",
                      "options":{
                        "easing":"slideRight",
                        "duration":500,
                        "showType":"none"}}},
{
                    "objectPath":["d665b50486544f27bd6386fd4f85902d"],
                    "fadeInfo":{
                      "fadeType":"show",
                      "options":{
                        "showType":"none"}}}]},
{
                "action":"fadeWidget",
                "description":"隐藏 75",
                "objectsToFades":[{
                    "objectPath":["803f028e51c44421bcea4d7b6fe2187f"],
                    "fadeInfo":{
                      "fadeType":"hide",
                      "options":{
                        "showType":"none"}}}]},
{
                "action":"linkWindow",
                "description":"在 当前窗口 打开 menu",
                "target":{
                  "targetType":"page",
                  "url":"menu.html",
                  "includeVariables":true},
                "linkType":"current"}]}]}},
    "diagram":{
      "objects":[{
          "id":"40f9eaf54200418db8e754c16b70f6c7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1673,
              "height":1000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cff31754a4b40c8bc368bc65c64fc13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1673,
                  "height":1000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/loading/u0.jpg"}},
{
          "id":"f61d8f12be74408f838a85e1417e1df7",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":196.5,
              "y":140.5},
            "size":{
              "width":1280,
              "height":719}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"45e48126fa754429babdfe8acd056637",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f20a7971f0ac4345b502915429f3bcad",
                  "label":"",
                  "parentDynamicPanel":"f61d8f12be74408f838a85e1417e1df7",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1280,
                      "height":720},
                    "cornerRadiusTopLeft":"20"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"500f548ca7b449839290b7c1c2dcc10f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f61d8f12be74408f838a85e1417e1df7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1280,
                          "height":720},
                        "cornerRadiusTopLeft":"20"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/loading/u3.png"}},
{
                  "id":"7612f3b16c254fc9a603622a0a586413",
                  "label":"空条",
                  "parentDynamicPanel":"f61d8f12be74408f838a85e1417e1df7",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":140,
                      "y":600},
                    "size":{
                      "width":1000,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ba9cca9fafe242679b0581ae60629f03",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f61d8f12be74408f838a85e1417e1df7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":140,
                          "y":600},
                        "size":{
                          "width":1000,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/loading/空条_u5.png"}},
{
                  "id":"e3073c2586f8492ab3c0cbe2575e1916",
                  "label":"1",
                  "parentDynamicPanel":"f61d8f12be74408f838a85e1417e1df7",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF009DD9},
                    "location":{
                      "x":140,
                      "y":600},
                    "size":{
                      "width":200,
                      "height":30},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"14c0bb3b90fb41dd9af3e84deb80de0f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f61d8f12be74408f838a85e1417e1df7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF009DD9},
                        "location":{
                          "x":140,
                          "y":600},
                        "size":{
                          "width":200,
                          "height":30},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/loading/1_u7.png"}},
{
                  "id":"d1ed500786c44acd8f0523c752a3a3b9",
                  "label":"25",
                  "parentDynamicPanel":"f61d8f12be74408f838a85e1417e1df7",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF009DD9},
                    "location":{
                      "x":339,
                      "y":600},
                    "size":{
                      "width":200,
                      "height":30},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5bd226ff5e77455f82b1db6e9c18295f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f61d8f12be74408f838a85e1417e1df7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF009DD9},
                        "location":{
                          "x":339,
                          "y":600},
                        "size":{
                          "width":200,
                          "height":30},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/loading/1_u7.png"}},
{
                  "id":"575611b2585f43a1aed9677af23c3c85",
                  "label":"50",
                  "parentDynamicPanel":"f61d8f12be74408f838a85e1417e1df7",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF009DD9},
                    "location":{
                      "x":538,
                      "y":600},
                    "size":{
                      "width":200,
                      "height":30},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"522b9408a66840428e495c360e80b242",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f61d8f12be74408f838a85e1417e1df7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF009DD9},
                        "location":{
                          "x":538,
                          "y":600},
                        "size":{
                          "width":200,
                          "height":30},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/loading/1_u7.png"}},
{
                  "id":"2ce8578607bd4c718550b6ab40b95fa8",
                  "label":"75",
                  "parentDynamicPanel":"f61d8f12be74408f838a85e1417e1df7",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF009DD9},
                    "location":{
                      "x":737,
                      "y":600},
                    "size":{
                      "width":200,
                      "height":30},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"da8cc4a76e9045e3af1701c34870ddcd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f61d8f12be74408f838a85e1417e1df7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF009DD9},
                        "location":{
                          "x":737,
                          "y":600},
                        "size":{
                          "width":200,
                          "height":30},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/loading/1_u7.png"}},
{
                  "id":"37a1a6faf7894112a3a893d8b03164de",
                  "label":"100",
                  "parentDynamicPanel":"f61d8f12be74408f838a85e1417e1df7",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF009DD9},
                    "location":{
                      "x":936,
                      "y":600},
                    "size":{
                      "width":200,
                      "height":30},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"27af10d3097f4897aaffd093486d21d2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f61d8f12be74408f838a85e1417e1df7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF009DD9},
                        "location":{
                          "x":936,
                          "y":600},
                        "size":{
                          "width":200,
                          "height":30},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/loading/1_u7.png"}},
{
                  "id":"d6b3ca3ec8d541da8c5de2f01f54194c",
                  "label":"",
                  "parentDynamicPanel":"f61d8f12be74408f838a85e1417e1df7",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":587.5,
                      "y":600},
                    "size":{
                      "width":101,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"0022b25db42b4928a6f6b383baaca502",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"83496704048444b784de9b3eef4aae98",
                          "label":"0",
                          "parentDynamicPanel":"d6b3ca3ec8d541da8c5de2f01f54194c",
                          "type":"buttonShape",
                          "styleType":"h2",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "location":{
                              "x":34,
                              "y":6},
                            "size":{
                              "width":26,
                              "height":19}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"48a74c3116aa41b980d0661fadb5c1f5",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"d6b3ca3ec8d541da8c5de2f01f54194c",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"16px",
                                "location":{
                                  "x":34,
                                  "y":6},
                                "size":{
                                  "width":26,
                                  "height":19}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"021f2d64b29c46c19093b6c8bcecafe6",
                          "label":"20",
                          "parentDynamicPanel":"d6b3ca3ec8d541da8c5de2f01f54194c",
                          "type":"buttonShape",
                          "styleType":"h2",
                          "visible":false,
                          "style":{
                            "fontSize":"16px",
                            "location":{
                              "x":30,
                              "y":6},
                            "size":{
                              "width":35,
                              "height":19},
                            "visible":false},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"5fbcd00e9c6d403e99c42205c72e1287",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"d6b3ca3ec8d541da8c5de2f01f54194c",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":false,
                              "style":{
                                "fontSize":"16px",
                                "location":{
                                  "x":30,
                                  "y":6},
                                "size":{
                                  "width":35,
                                  "height":19},
                                "visible":false},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"e4edf30b18e04564b837055c70551f9e",
                          "label":"50",
                          "parentDynamicPanel":"d6b3ca3ec8d541da8c5de2f01f54194c",
                          "type":"buttonShape",
                          "styleType":"h2",
                          "visible":false,
                          "style":{
                            "fontSize":"16px",
                            "location":{
                              "x":30,
                              "y":6},
                            "size":{
                              "width":35,
                              "height":19},
                            "visible":false},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"1b1ce2cbcdc9411da3fd6248ae17fc3f",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"d6b3ca3ec8d541da8c5de2f01f54194c",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":false,
                              "style":{
                                "fontSize":"16px",
                                "location":{
                                  "x":30,
                                  "y":6},
                                "size":{
                                  "width":35,
                                  "height":19},
                                "visible":false},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"803f028e51c44421bcea4d7b6fe2187f",
                          "label":"75",
                          "parentDynamicPanel":"d6b3ca3ec8d541da8c5de2f01f54194c",
                          "type":"buttonShape",
                          "styleType":"h2",
                          "visible":false,
                          "style":{
                            "fontSize":"16px",
                            "location":{
                              "x":30,
                              "y":6},
                            "size":{
                              "width":35,
                              "height":19},
                            "visible":false},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"31d4b68df5b04458a41a19ae5eca9fa6",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"d6b3ca3ec8d541da8c5de2f01f54194c",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":false,
                              "style":{
                                "fontSize":"16px",
                                "location":{
                                  "x":30,
                                  "y":6},
                                "size":{
                                  "width":35,
                                  "height":19},
                                "visible":false},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"d665b50486544f27bd6386fd4f85902d",
                          "label":"100",
                          "parentDynamicPanel":"d6b3ca3ec8d541da8c5de2f01f54194c",
                          "type":"buttonShape",
                          "styleType":"h2",
                          "visible":false,
                          "style":{
                            "fontSize":"16px",
                            "location":{
                              "x":30,
                              "y":6},
                            "size":{
                              "width":44,
                              "height":19},
                            "visible":false},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"256a121255ca4663af71f7f294d9a55c",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"d6b3ca3ec8d541da8c5de2f01f54194c",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":false,
                              "style":{
                                "fontSize":"16px",
                                "location":{
                                  "x":30,
                                  "y":6},
                                "size":{
                                  "width":44,
                                  "height":19},
                                "visible":false},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}}]}]}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "40f9eaf54200418db8e754c16b70f6c7":{
      "scriptId":"u0"},
    "1cff31754a4b40c8bc368bc65c64fc13":{
      "scriptId":"u1"},
    "f61d8f12be74408f838a85e1417e1df7":{
      "scriptId":"u2"},
    "f20a7971f0ac4345b502915429f3bcad":{
      "scriptId":"u3"},
    "500f548ca7b449839290b7c1c2dcc10f":{
      "scriptId":"u4"},
    "7612f3b16c254fc9a603622a0a586413":{
      "scriptId":"u5"},
    "ba9cca9fafe242679b0581ae60629f03":{
      "scriptId":"u6"},
    "e3073c2586f8492ab3c0cbe2575e1916":{
      "scriptId":"u7"},
    "14c0bb3b90fb41dd9af3e84deb80de0f":{
      "scriptId":"u8"},
    "d1ed500786c44acd8f0523c752a3a3b9":{
      "scriptId":"u9"},
    "5bd226ff5e77455f82b1db6e9c18295f":{
      "scriptId":"u10"},
    "575611b2585f43a1aed9677af23c3c85":{
      "scriptId":"u11"},
    "522b9408a66840428e495c360e80b242":{
      "scriptId":"u12"},
    "2ce8578607bd4c718550b6ab40b95fa8":{
      "scriptId":"u13"},
    "da8cc4a76e9045e3af1701c34870ddcd":{
      "scriptId":"u14"},
    "37a1a6faf7894112a3a893d8b03164de":{
      "scriptId":"u15"},
    "27af10d3097f4897aaffd093486d21d2":{
      "scriptId":"u16"},
    "d6b3ca3ec8d541da8c5de2f01f54194c":{
      "scriptId":"u17"},
    "83496704048444b784de9b3eef4aae98":{
      "scriptId":"u18"},
    "48a74c3116aa41b980d0661fadb5c1f5":{
      "scriptId":"u19"},
    "021f2d64b29c46c19093b6c8bcecafe6":{
      "scriptId":"u20"},
    "5fbcd00e9c6d403e99c42205c72e1287":{
      "scriptId":"u21"},
    "e4edf30b18e04564b837055c70551f9e":{
      "scriptId":"u22"},
    "1b1ce2cbcdc9411da3fd6248ae17fc3f":{
      "scriptId":"u23"},
    "803f028e51c44421bcea4d7b6fe2187f":{
      "scriptId":"u24"},
    "31d4b68df5b04458a41a19ae5eca9fa6":{
      "scriptId":"u25"},
    "d665b50486544f27bd6386fd4f85902d":{
      "scriptId":"u26"},
    "256a121255ca4663af71f7f294d9a55c":{
      "scriptId":"u27"}}});