$axure.loadCurrentPage({
  "url":"main.html",
  "generationDate":new Date(1460297998619.12),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"11bc6a8b37844576bd4e10f533e6fc56",
    "type":"Axure:Page",
    "name":"main",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"607b30b7095d48448e170e3dbe116821",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1673,
              "height":1000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"580c90c3558b42ef9fc2f7d786e90555",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1673,
                  "height":1000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/loading/u0.jpg"}},
{
          "id":"6d0e7d1832bb4f8d84d670fe35e98f7f",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":197,
              "y":138},
            "size":{
              "width":1280,
              "height":719}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"8a7f40838976478482d5061c1f4b4e07",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"1b57fee5f42d4605bc9b4367c37132e0",
                  "label":"",
                  "parentDynamicPanel":"6d0e7d1832bb4f8d84d670fe35e98f7f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":-1},
                    "size":{
                      "width":1280,
                      "height":720},
                    "cornerRadiusTopLeft":"20"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"17e7410320904bfdb6858094eb07912a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d0e7d1832bb4f8d84d670fe35e98f7f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":-1},
                        "size":{
                          "width":1280,
                          "height":720},
                        "cornerRadiusTopLeft":"20"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/loading/u3.png"}},
{
                  "id":"c1157ac8d30b488c80d08f27a2ffb193",
                  "label":"",
                  "parentDynamicPanel":"6d0e7d1832bb4f8d84d670fe35e98f7f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "location":{
                      "x":1060,
                      "y":120},
                    "size":{
                      "width":130,
                      "height":130}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c1e37c0b711e4252bbafd43e0ef78bd8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d0e7d1832bb4f8d84d670fe35e98f7f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "location":{
                          "x":1060,
                          "y":120},
                        "size":{
                          "width":130,
                          "height":130}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 1,<br>菜单,<br>隐藏 2,<br>3",
                              "objectsToFades":[{
                                  "objectPath":["9979cd533ae4422d886a27645949a641"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["ce24fa1ecf91493aa8d5c59b82d2ef5a"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["6a8f5afdb5834f06bcdb19908f086373"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["dfa361932e82489881659d3669813fd9"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/main/u5.png"}},
{
                  "id":"1dcb9ed4ff66477a8004e0451925393d",
                  "label":"",
                  "parentDynamicPanel":"6d0e7d1832bb4f8d84d670fe35e98f7f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "location":{
                      "x":1060,
                      "y":260},
                    "size":{
                      "width":130,
                      "height":130}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ee8afef5d8934f7cb47f1a25cb09fd6c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d0e7d1832bb4f8d84d670fe35e98f7f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "location":{
                          "x":1060,
                          "y":260},
                        "size":{
                          "width":130,
                          "height":130}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 2,<br>菜单,<br>隐藏 1,<br>3",
                              "objectsToFades":[{
                                  "objectPath":["9979cd533ae4422d886a27645949a641"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["ce24fa1ecf91493aa8d5c59b82d2ef5a"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["6a8f5afdb5834f06bcdb19908f086373"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["dfa361932e82489881659d3669813fd9"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/main/u5.png"}},
{
                  "id":"0ce069b3087148b78bb68efd032e4890",
                  "label":"",
                  "parentDynamicPanel":"6d0e7d1832bb4f8d84d670fe35e98f7f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "location":{
                      "x":1060,
                      "y":404},
                    "size":{
                      "width":130,
                      "height":126}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4c9fdd289102431ba2d2309996aa8388",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d0e7d1832bb4f8d84d670fe35e98f7f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "location":{
                          "x":1060,
                          "y":404},
                        "size":{
                          "width":130,
                          "height":126}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 3,<br>菜单,<br>隐藏 1,<br>2",
                              "objectsToFades":[{
                                  "objectPath":["9979cd533ae4422d886a27645949a641"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["ce24fa1ecf91493aa8d5c59b82d2ef5a"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["6a8f5afdb5834f06bcdb19908f086373"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["dfa361932e82489881659d3669813fd9"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/main/u9.png"}},
{
                  "id":"9298c1abb283400ebe57fcc1c16e7577",
                  "label":"",
                  "parentDynamicPanel":"6d0e7d1832bb4f8d84d670fe35e98f7f",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":1160,
                      "y":15},
                    "size":{
                      "width":100,
                      "height":55}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 暂停",
                              "objectsToFades":[{
                                  "objectPath":["6e0f1ce3b50349d5b927730083e46fe9"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"9979cd533ae4422d886a27645949a641",
                  "label":"1",
                  "parentDynamicPanel":"6d0e7d1832bb4f8d84d670fe35e98f7f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF0000},
                    "location":{
                      "x":985,
                      "y":155},
                    "size":{
                      "width":90,
                      "height":60},
                    "visible":false,
                    "rotation":"270",
                    "textRotation":"270"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2435fea4cef04e8b864acb96397d5e90",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d0e7d1832bb4f8d84d670fe35e98f7f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF0000},
                        "location":{
                          "x":985,
                          "y":155},
                        "size":{
                          "width":90,
                          "height":60},
                        "visible":false,
                        "rotation":"270",
                        "textRotation":"270"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/role/1_u13.png"}},
{
                  "id":"ce24fa1ecf91493aa8d5c59b82d2ef5a",
                  "label":"2",
                  "parentDynamicPanel":"6d0e7d1832bb4f8d84d670fe35e98f7f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF0000},
                    "location":{
                      "x":985,
                      "y":295},
                    "size":{
                      "width":90,
                      "height":60},
                    "visible":false,
                    "rotation":"270",
                    "textRotation":"270"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"efee0136d4044c2ea76ce0efc44bdfad",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d0e7d1832bb4f8d84d670fe35e98f7f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF0000},
                        "location":{
                          "x":985,
                          "y":295},
                        "size":{
                          "width":90,
                          "height":60},
                        "visible":false,
                        "rotation":"270",
                        "textRotation":"270"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/role/1_u13.png"}},
{
                  "id":"6a8f5afdb5834f06bcdb19908f086373",
                  "label":"3",
                  "parentDynamicPanel":"6d0e7d1832bb4f8d84d670fe35e98f7f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF0000},
                    "location":{
                      "x":985,
                      "y":437},
                    "size":{
                      "width":90,
                      "height":60},
                    "visible":false,
                    "rotation":"270",
                    "textRotation":"270"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"290a203cf499493da975693f2dd9dd16",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d0e7d1832bb4f8d84d670fe35e98f7f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF0000},
                        "location":{
                          "x":985,
                          "y":437},
                        "size":{
                          "width":90,
                          "height":60},
                        "visible":false,
                        "rotation":"270",
                        "textRotation":"270"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/role/1_u13.png"}},
{
                  "id":"dfa361932e82489881659d3669813fd9",
                  "label":"菜单",
                  "parentDynamicPanel":"6d0e7d1832bb4f8d84d670fe35e98f7f",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":496,
                      "y":170},
                    "size":{
                      "width":290,
                      "height":350},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"4c38244432b143878e04487bcb5017bb",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"297be957a70f43f9a6ae73d6c668c858",
                          "label":"",
                          "parentDynamicPanel":"dfa361932e82489881659d3669813fd9",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":290,
                              "height":350},
                            "cornerRadiusTopLeft":"20"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"73484ab6d91f48c7bb74b1118fa9c765",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"dfa361932e82489881659d3669813fd9",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":290,
                                  "height":350},
                                "cornerRadiusTopLeft":"20"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/main/u19.png"}},
{
                          "id":"9d45b01bbe3e4baf9ae3d3f2dec80958",
                          "label":"",
                          "parentDynamicPanel":"dfa361932e82489881659d3669813fd9",
                          "type":"buttonShape",
                          "styleType":"h1",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":112,
                              "y":14},
                            "size":{
                              "width":65,
                              "height":37}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"f2e564740f68462cbe65a6d4f0a65f27",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"dfa361932e82489881659d3669813fd9",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":112,
                                  "y":14},
                                "size":{
                                  "width":65,
                                  "height":37}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"6123c6b6b8864714942d405fb9096d21",
                          "label":"",
                          "parentDynamicPanel":"dfa361932e82489881659d3669813fd9",
                          "type":"button",
                          "styleType":"button",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":94.5,
                              "y":85},
                            "size":{
                              "width":100,
                              "height":25}},
                          "adaptiveStyles":{
},
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"fadeWidget",
                                      "description":"显示 普通攻击,<br>隐藏 菜单",
                                      "objectsToFades":[{
                                          "objectPath":["dfa361932e82489881659d3669813fd9"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}},
{
                                          "objectPath":["11be70f035e04155a33324fbc7aa6755"],
                                          "fadeInfo":{
                                            "fadeType":"show",
                                            "options":{
                                              "showType":"none"}}}]},
{
                                      "action":"wait",
                                      "description":"等待3000毫秒",
                                      "waitTime":3000},
{
                                      "action":"fadeWidget",
                                      "description":"隐藏 普通攻击",
                                      "objectsToFades":[{
                                          "objectPath":["11be70f035e04155a33324fbc7aa6755"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}}]}]}]}},
                          "tabbable":true},
{
                          "id":"a41e3a1ad70b420b8ab309cb10dca240",
                          "label":"",
                          "parentDynamicPanel":"dfa361932e82489881659d3669813fd9",
                          "type":"button",
                          "styleType":"button",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":94,
                              "y":130},
                            "size":{
                              "width":100,
                              "height":25}},
                          "adaptiveStyles":{
},
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"fadeWidget",
                                      "description":"隐藏 菜单",
                                      "objectsToFades":[{
                                          "objectPath":["dfa361932e82489881659d3669813fd9"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}}]},
{
                                      "action":"fadeWidget",
                                      "description":"显示 连招,<br>普通攻击",
                                      "objectsToFades":[{
                                          "objectPath":["c39ed460243d4f1480fc376479590915"],
                                          "fadeInfo":{
                                            "fadeType":"show",
                                            "options":{
                                              "showType":"none"}}},
{
                                          "objectPath":["7ed785740c5347069d3f6dca972a2826"],
                                          "fadeInfo":{
                                            "fadeType":"show",
                                            "options":{
                                              "showType":"none"}}}]},
{
                                      "action":"wait",
                                      "description":"等待4000毫秒",
                                      "waitTime":4000},
{
                                      "action":"fadeWidget",
                                      "description":"隐藏 连招,<br>普通攻击",
                                      "objectsToFades":[{
                                          "objectPath":["c39ed460243d4f1480fc376479590915"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}},
{
                                          "objectPath":["7ed785740c5347069d3f6dca972a2826"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}}]}]}]}},
                          "tabbable":true},
{
                          "id":"9d42407d48654f2d875eee218e7e4041",
                          "label":"",
                          "parentDynamicPanel":"dfa361932e82489881659d3669813fd9",
                          "type":"button",
                          "styleType":"button",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":94,
                              "y":170},
                            "size":{
                              "width":100,
                              "height":25}},
                          "adaptiveStyles":{
},
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"fadeWidget",
                                      "description":"隐藏 菜单",
                                      "objectsToFades":[{
                                          "objectPath":["dfa361932e82489881659d3669813fd9"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}}]},
{
                                      "action":"fadeWidget",
                                      "description":"显示 连招,<br>组合",
                                      "objectsToFades":[{
                                          "objectPath":["c39ed460243d4f1480fc376479590915"],
                                          "fadeInfo":{
                                            "fadeType":"show",
                                            "options":{
                                              "showType":"none"}}},
{
                                          "objectPath":["a50cb25a4cec439c9b1ad4f02a762649"],
                                          "fadeInfo":{
                                            "fadeType":"show",
                                            "options":{
                                              "showType":"none"}}}]},
{
                                      "action":"wait",
                                      "description":"等待4000毫秒",
                                      "waitTime":4000},
{
                                      "action":"fadeWidget",
                                      "description":"隐藏 连招,<br>组合",
                                      "objectsToFades":[{
                                          "objectPath":["c39ed460243d4f1480fc376479590915"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}},
{
                                          "objectPath":["a50cb25a4cec439c9b1ad4f02a762649"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}}]}]}]}},
                          "tabbable":true},
{
                          "id":"36ec434c9161485897269b827e5508c5",
                          "label":"",
                          "parentDynamicPanel":"dfa361932e82489881659d3669813fd9",
                          "type":"button",
                          "styleType":"button",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":94,
                              "y":215},
                            "size":{
                              "width":100,
                              "height":25}},
                          "adaptiveStyles":{
},
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"fadeWidget",
                                      "description":"显示 换人,<br>换人",
                                      "objectsToFades":[{
                                          "objectPath":["b8312b3df75f4ac6b886bb01bc1ef134"],
                                          "fadeInfo":{
                                            "fadeType":"show",
                                            "options":{
                                              "showType":"none"}}},
{
                                          "objectPath":["a20f6f75e5ec4071916d58ee017dd5fe"],
                                          "fadeInfo":{
                                            "fadeType":"show",
                                            "options":{
                                              "showType":"none"}}}]},
{
                                      "action":"fadeWidget",
                                      "description":"隐藏 菜单,<br>换人",
                                      "objectsToFades":[{
                                          "objectPath":["dfa361932e82489881659d3669813fd9"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}},
{
                                          "objectPath":["a20f6f75e5ec4071916d58ee017dd5fe"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}}]}]}]}},
                          "tabbable":true}]}]},
{
                  "id":"f9a547f009be4040b72359611ef02694",
                  "label":"文字",
                  "parentDynamicPanel":"6d0e7d1832bb4f8d84d670fe35e98f7f",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":496,
                      "y":154},
                    "size":{
                      "width":290,
                      "height":70}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"2b2403935f104e41a72b4875df5f60a7",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"11be70f035e04155a33324fbc7aa6755",
                          "label":"普通攻击",
                          "parentDynamicPanel":"f9a547f009be4040b72359611ef02694",
                          "type":"buttonShape",
                          "styleType":"h2",
                          "visible":false,
                          "style":{
                            "location":{
                              "x":35,
                              "y":21},
                            "size":{
                              "width":195,
                              "height":28},
                            "visible":false},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"cec11c136c924deab157f82cea551c4b",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"f9a547f009be4040b72359611ef02694",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":false,
                              "style":{
                                "location":{
                                  "x":35,
                                  "y":21},
                                "size":{
                                  "width":195,
                                  "height":28},
                                "visible":false},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"7ed785740c5347069d3f6dca972a2826",
                          "label":"普通攻击",
                          "parentDynamicPanel":"f9a547f009be4040b72359611ef02694",
                          "type":"buttonShape",
                          "styleType":"h2",
                          "visible":false,
                          "style":{
                            "location":{
                              "x":35,
                              "y":21},
                            "size":{
                              "width":147,
                              "height":28},
                            "visible":false},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"7d3f1384fed043998203e8c0e22e589c",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"f9a547f009be4040b72359611ef02694",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":false,
                              "style":{
                                "location":{
                                  "x":35,
                                  "y":21},
                                "size":{
                                  "width":147,
                                  "height":28},
                                "visible":false},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"a50cb25a4cec439c9b1ad4f02a762649",
                          "label":"组合",
                          "parentDynamicPanel":"f9a547f009be4040b72359611ef02694",
                          "type":"buttonShape",
                          "styleType":"h2",
                          "visible":false,
                          "style":{
                            "location":{
                              "x":35,
                              "y":21},
                            "size":{
                              "width":147,
                              "height":28},
                            "visible":false},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"bcb6527ccd2444a6bc0eedd0feeb8d5c",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"f9a547f009be4040b72359611ef02694",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":false,
                              "style":{
                                "location":{
                                  "x":35,
                                  "y":21},
                                "size":{
                                  "width":147,
                                  "height":28},
                                "visible":false},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"a20f6f75e5ec4071916d58ee017dd5fe",
                          "label":"换人",
                          "parentDynamicPanel":"f9a547f009be4040b72359611ef02694",
                          "type":"buttonShape",
                          "styleType":"h2",
                          "visible":false,
                          "style":{
                            "location":{
                              "x":108,
                              "y":21},
                            "size":{
                              "width":49,
                              "height":28},
                            "visible":false},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"af55f61f30cf4c6a9be71a77e9a5ab40",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"f9a547f009be4040b72359611ef02694",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":false,
                              "style":{
                                "location":{
                                  "x":108,
                                  "y":21},
                                "size":{
                                  "width":49,
                                  "height":28},
                                "visible":false},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}}]}]},
{
                  "id":"c39ed460243d4f1480fc376479590915",
                  "label":"连招",
                  "parentDynamicPanel":"6d0e7d1832bb4f8d84d670fe35e98f7f",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":454,
                      "y":240},
                    "size":{
                      "width":374,
                      "height":440},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"d751275904f148fcb8e70202a1aa3159",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"db21368ca86b43d48c25d37c1e159d42",
                          "label":"",
                          "parentDynamicPanel":"c39ed460243d4f1480fc376479590915",
                          "type":"button",
                          "styleType":"button",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":140,
                              "y":20},
                            "size":{
                              "width":50,
                              "height":50}},
                          "adaptiveStyles":{
}},
{
                          "id":"d93717cb31924e4eb49c7b6f3be8eaf2",
                          "label":"",
                          "parentDynamicPanel":"c39ed460243d4f1480fc376479590915",
                          "type":"button",
                          "styleType":"button",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":170,
                              "y":130},
                            "size":{
                              "width":50,
                              "height":50}},
                          "adaptiveStyles":{
}},
{
                          "id":"65e35fa3a2354b74a7bc586c5cf47a40",
                          "label":"",
                          "parentDynamicPanel":"c39ed460243d4f1480fc376479590915",
                          "type":"button",
                          "styleType":"button",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":200,
                              "y":70},
                            "size":{
                              "width":50,
                              "height":50}},
                          "adaptiveStyles":{
}},
{
                          "id":"8af8a5fdd7e0435ba55f9eede26b1c5f",
                          "label":"",
                          "parentDynamicPanel":"c39ed460243d4f1480fc376479590915",
                          "type":"button",
                          "styleType":"button",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":100,
                              "y":130},
                            "size":{
                              "width":50,
                              "height":50}},
                          "adaptiveStyles":{
}},
{
                          "id":"aed75068162b463c8ab888d023292215",
                          "label":"",
                          "parentDynamicPanel":"c39ed460243d4f1480fc376479590915",
                          "type":"button",
                          "styleType":"button",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":80,
                              "y":70},
                            "size":{
                              "width":50,
                              "height":50}},
                          "adaptiveStyles":{
}},
{
                          "id":"e2187f09bc9243c9bf8239628a3c7e7f",
                          "label":"",
                          "parentDynamicPanel":"c39ed460243d4f1480fc376479590915",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":25,
                              "y":360},
                            "size":{
                              "width":315,
                              "height":60}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"069510b2d527413093372c65c21a4aa9",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"c39ed460243d4f1480fc376479590915",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":25,
                                  "y":360},
                                "size":{
                                  "width":315,
                                  "height":60}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/main/u42.png"}}]}]},
{
                  "id":"b8312b3df75f4ac6b886bb01bc1ef134",
                  "label":"换人",
                  "parentDynamicPanel":"6d0e7d1832bb4f8d84d670fe35e98f7f",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":454,
                      "y":290},
                    "size":{
                      "width":374,
                      "height":200},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"aa0beeffd2304dc79456fe3e17b914b6",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"6a0f4156c72c488784a9a7bf2ec6a592",
                          "label":"",
                          "parentDynamicPanel":"b8312b3df75f4ac6b886bb01bc1ef134",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":370,
                              "height":200},
                            "cornerRadiusTopLeft":"10"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"08532200f4d44177a4d198f91e92733c",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"b8312b3df75f4ac6b886bb01bc1ef134",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":370,
                                  "height":200},
                                "cornerRadiusTopLeft":"10"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/main/u45.png"}},
{
                          "id":"b933b8b8d6be4cd096f244553a36282c",
                          "label":"",
                          "parentDynamicPanel":"b8312b3df75f4ac6b886bb01bc1ef134",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":23,
                              "y":20},
                            "size":{
                              "width":70,
                              "height":150}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"79ec2f244c074b5faec3e402a15c8b6f",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"b8312b3df75f4ac6b886bb01bc1ef134",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":23,
                                  "y":20},
                                "size":{
                                  "width":70,
                                  "height":150}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"fadeWidget",
                                      "description":"隐藏 换人",
                                      "objectsToFades":[{
                                          "objectPath":["b8312b3df75f4ac6b886bb01bc1ef134"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}}]}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/main/u47.png"}},
{
                          "id":"e8799fac94e447ac966dc57a220d3650",
                          "label":"",
                          "parentDynamicPanel":"b8312b3df75f4ac6b886bb01bc1ef134",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":103,
                              "y":20},
                            "size":{
                              "width":70,
                              "height":150}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"7b004490861943eab3b68e08145ec189",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"b8312b3df75f4ac6b886bb01bc1ef134",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":103,
                                  "y":20},
                                "size":{
                                  "width":70,
                                  "height":150}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"fadeWidget",
                                      "description":"隐藏 换人",
                                      "objectsToFades":[{
                                          "objectPath":["b8312b3df75f4ac6b886bb01bc1ef134"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}}]}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/main/u47.png"}},
{
                          "id":"396fa93ce64642c9a6805f44073f8645",
                          "label":"",
                          "parentDynamicPanel":"b8312b3df75f4ac6b886bb01bc1ef134",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":183,
                              "y":20},
                            "size":{
                              "width":70,
                              "height":150}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"d71917d1570a4bec80ea7b7ea7b3e176",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"b8312b3df75f4ac6b886bb01bc1ef134",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":183,
                                  "y":20},
                                "size":{
                                  "width":70,
                                  "height":150}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"fadeWidget",
                                      "description":"隐藏 换人",
                                      "objectsToFades":[{
                                          "objectPath":["b8312b3df75f4ac6b886bb01bc1ef134"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}}]}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/main/u47.png"}},
{
                          "id":"1698827ec4a542c38c1885248b741cca",
                          "label":"",
                          "parentDynamicPanel":"b8312b3df75f4ac6b886bb01bc1ef134",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":263,
                              "y":20},
                            "size":{
                              "width":70,
                              "height":150}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"e5736fc609024d6a96dc11c53f8bc1e2",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"b8312b3df75f4ac6b886bb01bc1ef134",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":263,
                                  "y":20},
                                "size":{
                                  "width":70,
                                  "height":150}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"fadeWidget",
                                      "description":"隐藏 换人",
                                      "objectsToFades":[{
                                          "objectPath":["b8312b3df75f4ac6b886bb01bc1ef134"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}}]}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/main/u47.png"}}]}]},
{
                  "id":"6e0f1ce3b50349d5b927730083e46fe9",
                  "label":"暂停",
                  "parentDynamicPanel":"6d0e7d1832bb4f8d84d670fe35e98f7f",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":359,
                      "y":144},
                    "size":{
                      "width":564,
                      "height":480},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"6593c93abfdc461e90c943f6e3f740d6",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"7d10e81ff2c0444584e1ef9f3061e75f",
                          "label":"",
                          "parentDynamicPanel":"6e0f1ce3b50349d5b927730083e46fe9",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":560,
                              "height":480},
                            "cornerRadiusTopLeft":"20"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"7fee836e089c4d1591c92d0813a5f0d4",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"6e0f1ce3b50349d5b927730083e46fe9",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":560,
                                  "height":480},
                                "cornerRadiusTopLeft":"20"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/main/u56.png"}},
{
                          "id":"7fd1b1cb457149168d544a4cf876b9da",
                          "label":"",
                          "parentDynamicPanel":"6e0f1ce3b50349d5b927730083e46fe9",
                          "type":"buttonShape",
                          "styleType":"h1",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":250,
                              "y":32},
                            "size":{
                              "width":65,
                              "height":37}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"1679f03a42e14897be36216b48bb2215",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"6e0f1ce3b50349d5b927730083e46fe9",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":250,
                                  "y":32},
                                "size":{
                                  "width":65,
                                  "height":37}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"53607e58acff45d9b527eedcb65221e3",
                          "label":"",
                          "parentDynamicPanel":"6e0f1ce3b50349d5b927730083e46fe9",
                          "type":"button",
                          "styleType":"button",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":182,
                              "y":228},
                            "size":{
                              "width":200,
                              "height":50}},
                          "adaptiveStyles":{
},
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"fadeWidget",
                                      "description":"隐藏 暂停",
                                      "objectsToFades":[{
                                          "objectPath":["6e0f1ce3b50349d5b927730083e46fe9"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}}]}]}]}},
                          "tabbable":true},
{
                          "id":"b85ddbf5645c4bcfb46f268689d60192",
                          "label":"音效：开",
                          "parentDynamicPanel":"6e0f1ce3b50349d5b927730083e46fe9",
                          "type":"button",
                          "styleType":"button",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":178,
                              "y":148},
                            "size":{
                              "width":200,
                              "height":50}},
                          "adaptiveStyles":{
},
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"fadeWidget",
                                      "description":"切换 音效：开,<br>音效：关",
                                      "objectsToFades":[{
                                          "objectPath":["b85ddbf5645c4bcfb46f268689d60192"],
                                          "fadeInfo":{
                                            "fadeType":"toggle",
                                            "options":{
                                              "showType":"none"}}},
{
                                          "objectPath":["a95350a6290648a2bc3563e628e483a7"],
                                          "fadeInfo":{
                                            "fadeType":"toggle",
                                            "options":{
                                              "showType":"none"}}}]}]}]}},
                          "tabbable":true},
{
                          "id":"a95350a6290648a2bc3563e628e483a7",
                          "label":"音效：关",
                          "parentDynamicPanel":"6e0f1ce3b50349d5b927730083e46fe9",
                          "type":"button",
                          "styleType":"button",
                          "visible":false,
                          "style":{
                            "location":{
                              "x":178,
                              "y":148},
                            "size":{
                              "width":200,
                              "height":50},
                            "visible":false},
                          "adaptiveStyles":{
},
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"fadeWidget",
                                      "description":"切换 音效：开,<br>音效：关",
                                      "objectsToFades":[{
                                          "objectPath":["b85ddbf5645c4bcfb46f268689d60192"],
                                          "fadeInfo":{
                                            "fadeType":"toggle",
                                            "options":{
                                              "showType":"none"}}},
{
                                          "objectPath":["a95350a6290648a2bc3563e628e483a7"],
                                          "fadeInfo":{
                                            "fadeType":"toggle",
                                            "options":{
                                              "showType":"none"}}}]}]}]}},
                          "tabbable":true}]}]}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "607b30b7095d48448e170e3dbe116821":{
      "scriptId":"u0"},
    "580c90c3558b42ef9fc2f7d786e90555":{
      "scriptId":"u1"},
    "6d0e7d1832bb4f8d84d670fe35e98f7f":{
      "scriptId":"u2"},
    "1b57fee5f42d4605bc9b4367c37132e0":{
      "scriptId":"u3"},
    "17e7410320904bfdb6858094eb07912a":{
      "scriptId":"u4"},
    "c1157ac8d30b488c80d08f27a2ffb193":{
      "scriptId":"u5"},
    "c1e37c0b711e4252bbafd43e0ef78bd8":{
      "scriptId":"u6"},
    "1dcb9ed4ff66477a8004e0451925393d":{
      "scriptId":"u7"},
    "ee8afef5d8934f7cb47f1a25cb09fd6c":{
      "scriptId":"u8"},
    "0ce069b3087148b78bb68efd032e4890":{
      "scriptId":"u9"},
    "4c9fdd289102431ba2d2309996aa8388":{
      "scriptId":"u10"},
    "9298c1abb283400ebe57fcc1c16e7577":{
      "scriptId":"u11"},
    "9979cd533ae4422d886a27645949a641":{
      "scriptId":"u12"},
    "2435fea4cef04e8b864acb96397d5e90":{
      "scriptId":"u13"},
    "ce24fa1ecf91493aa8d5c59b82d2ef5a":{
      "scriptId":"u14"},
    "efee0136d4044c2ea76ce0efc44bdfad":{
      "scriptId":"u15"},
    "6a8f5afdb5834f06bcdb19908f086373":{
      "scriptId":"u16"},
    "290a203cf499493da975693f2dd9dd16":{
      "scriptId":"u17"},
    "dfa361932e82489881659d3669813fd9":{
      "scriptId":"u18"},
    "297be957a70f43f9a6ae73d6c668c858":{
      "scriptId":"u19"},
    "73484ab6d91f48c7bb74b1118fa9c765":{
      "scriptId":"u20"},
    "9d45b01bbe3e4baf9ae3d3f2dec80958":{
      "scriptId":"u21"},
    "f2e564740f68462cbe65a6d4f0a65f27":{
      "scriptId":"u22"},
    "6123c6b6b8864714942d405fb9096d21":{
      "scriptId":"u23"},
    "a41e3a1ad70b420b8ab309cb10dca240":{
      "scriptId":"u24"},
    "9d42407d48654f2d875eee218e7e4041":{
      "scriptId":"u25"},
    "36ec434c9161485897269b827e5508c5":{
      "scriptId":"u26"},
    "f9a547f009be4040b72359611ef02694":{
      "scriptId":"u27"},
    "11be70f035e04155a33324fbc7aa6755":{
      "scriptId":"u28"},
    "cec11c136c924deab157f82cea551c4b":{
      "scriptId":"u29"},
    "7ed785740c5347069d3f6dca972a2826":{
      "scriptId":"u30"},
    "7d3f1384fed043998203e8c0e22e589c":{
      "scriptId":"u31"},
    "a50cb25a4cec439c9b1ad4f02a762649":{
      "scriptId":"u32"},
    "bcb6527ccd2444a6bc0eedd0feeb8d5c":{
      "scriptId":"u33"},
    "a20f6f75e5ec4071916d58ee017dd5fe":{
      "scriptId":"u34"},
    "af55f61f30cf4c6a9be71a77e9a5ab40":{
      "scriptId":"u35"},
    "c39ed460243d4f1480fc376479590915":{
      "scriptId":"u36"},
    "db21368ca86b43d48c25d37c1e159d42":{
      "scriptId":"u37"},
    "d93717cb31924e4eb49c7b6f3be8eaf2":{
      "scriptId":"u38"},
    "65e35fa3a2354b74a7bc586c5cf47a40":{
      "scriptId":"u39"},
    "8af8a5fdd7e0435ba55f9eede26b1c5f":{
      "scriptId":"u40"},
    "aed75068162b463c8ab888d023292215":{
      "scriptId":"u41"},
    "e2187f09bc9243c9bf8239628a3c7e7f":{
      "scriptId":"u42"},
    "069510b2d527413093372c65c21a4aa9":{
      "scriptId":"u43"},
    "b8312b3df75f4ac6b886bb01bc1ef134":{
      "scriptId":"u44"},
    "6a0f4156c72c488784a9a7bf2ec6a592":{
      "scriptId":"u45"},
    "08532200f4d44177a4d198f91e92733c":{
      "scriptId":"u46"},
    "b933b8b8d6be4cd096f244553a36282c":{
      "scriptId":"u47"},
    "79ec2f244c074b5faec3e402a15c8b6f":{
      "scriptId":"u48"},
    "e8799fac94e447ac966dc57a220d3650":{
      "scriptId":"u49"},
    "7b004490861943eab3b68e08145ec189":{
      "scriptId":"u50"},
    "396fa93ce64642c9a6805f44073f8645":{
      "scriptId":"u51"},
    "d71917d1570a4bec80ea7b7ea7b3e176":{
      "scriptId":"u52"},
    "1698827ec4a542c38c1885248b741cca":{
      "scriptId":"u53"},
    "e5736fc609024d6a96dc11c53f8bc1e2":{
      "scriptId":"u54"},
    "6e0f1ce3b50349d5b927730083e46fe9":{
      "scriptId":"u55"},
    "7d10e81ff2c0444584e1ef9f3061e75f":{
      "scriptId":"u56"},
    "7fee836e089c4d1591c92d0813a5f0d4":{
      "scriptId":"u57"},
    "7fd1b1cb457149168d544a4cf876b9da":{
      "scriptId":"u58"},
    "1679f03a42e14897be36216b48bb2215":{
      "scriptId":"u59"},
    "53607e58acff45d9b527eedcb65221e3":{
      "scriptId":"u60"},
    "b85ddbf5645c4bcfb46f268689d60192":{
      "scriptId":"u61"},
    "a95350a6290648a2bc3563e628e483a7":{
      "scriptId":"u62"}}});