$axure.loadCurrentPage({
  "url":"role.html",
  "generationDate":new Date(1460297998368.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7e1aa07d22ec41c9836d72fdf4473a3e",
    "type":"Axure:Page",
    "name":"role",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"af3e1c0287e84689b3e15ccca0b0185f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1673,
              "height":1000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d64ba295096424b91373f6394500e6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1673,
                  "height":1000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/loading/u0.jpg"}},
{
          "id":"54677eb7ef5446178a43cee0eee99a9a",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":197,
              "y":138},
            "size":{
              "width":1280,
              "height":719}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"60f9d862c03744b7a86402de54c5236f",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"fc6f5243773d413b9c002cff7f54ab45",
                  "label":"",
                  "parentDynamicPanel":"54677eb7ef5446178a43cee0eee99a9a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":-1},
                    "size":{
                      "width":1280,
                      "height":720},
                    "cornerRadiusTopLeft":"20"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2474c754222b44708e3e2b9cce9e1cee",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"54677eb7ef5446178a43cee0eee99a9a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":-1},
                        "size":{
                          "width":1280,
                          "height":720},
                        "cornerRadiusTopLeft":"20"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/loading/u3.png"}},
{
                  "id":"bb00d3f4c2304ca499de04ace47df153",
                  "label":"",
                  "parentDynamicPanel":"54677eb7ef5446178a43cee0eee99a9a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "location":{
                      "x":120,
                      "y":204},
                    "size":{
                      "width":230,
                      "height":350}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2ad926228d5d48aa8d25154174e8e7ee",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"54677eb7ef5446178a43cee0eee99a9a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "location":{
                          "x":120,
                          "y":204},
                        "size":{
                          "width":230,
                          "height":350}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 1,<br>隐藏 2,<br>3,<br>开始",
                              "objectsToFades":[{
                                  "objectPath":["d81425072d8f4db885030b7e8e5c5b19"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["f6ac4186ae384ed38576fc14c6aaa965"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["d5f5b449549f4a70bdf42d58234b8813"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["877c08924a2a409aaf058ee599e0eee1"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/role/u5.png"}},
{
                  "id":"2df597973c464c6da9bef5db8efc0e84",
                  "label":"",
                  "parentDynamicPanel":"54677eb7ef5446178a43cee0eee99a9a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "location":{
                      "x":525,
                      "y":204},
                    "size":{
                      "width":230,
                      "height":350}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"62d97edc2b194e98ac5ec95ea1691fa2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"54677eb7ef5446178a43cee0eee99a9a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "location":{
                          "x":525,
                          "y":204},
                        "size":{
                          "width":230,
                          "height":350}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 2,<br>隐藏 1,<br>3,<br>开始",
                              "objectsToFades":[{
                                  "objectPath":["d81425072d8f4db885030b7e8e5c5b19"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["f6ac4186ae384ed38576fc14c6aaa965"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["d5f5b449549f4a70bdf42d58234b8813"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["877c08924a2a409aaf058ee599e0eee1"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/role/u5.png"}},
{
                  "id":"d6f13649c6ec4f9b9c2c4a1f7ac2fcc9",
                  "label":"",
                  "parentDynamicPanel":"54677eb7ef5446178a43cee0eee99a9a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "location":{
                      "x":950,
                      "y":204},
                    "size":{
                      "width":230,
                      "height":350}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1bfd3fec9d3b49eca40c6a45caad8cd7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"54677eb7ef5446178a43cee0eee99a9a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "location":{
                          "x":950,
                          "y":204},
                        "size":{
                          "width":230,
                          "height":350}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 3,<br>隐藏 1,<br>2,<br>开始",
                              "objectsToFades":[{
                                  "objectPath":["d81425072d8f4db885030b7e8e5c5b19"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["f6ac4186ae384ed38576fc14c6aaa965"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["d5f5b449549f4a70bdf42d58234b8813"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["877c08924a2a409aaf058ee599e0eee1"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/role/u5.png"}},
{
                  "id":"5c2059500b3f4e8988cfe3a83ea39801",
                  "label":"",
                  "parentDynamicPanel":"54677eb7ef5446178a43cee0eee99a9a",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":1160,
                      "y":15},
                    "size":{
                      "width":100,
                      "height":55}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 level",
                              "target":{
                                "targetType":"page",
                                "url":"level.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true},
{
                  "id":"e515a9eb6c2444e28cf78d43c346a34c",
                  "label":"",
                  "parentDynamicPanel":"54677eb7ef5446178a43cee0eee99a9a",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":1160,
                      "y":640},
                    "size":{
                      "width":100,
                      "height":55}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 main",
                              "target":{
                                "targetType":"page",
                                "url":"main.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true},
{
                  "id":"d81425072d8f4db885030b7e8e5c5b19",
                  "label":"1",
                  "parentDynamicPanel":"54677eb7ef5446178a43cee0eee99a9a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF0000},
                    "location":{
                      "x":190,
                      "y":134},
                    "size":{
                      "width":90,
                      "height":60},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0abdbb01083645ef8f9a407a4a334925",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"54677eb7ef5446178a43cee0eee99a9a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF0000},
                        "location":{
                          "x":190,
                          "y":134},
                        "size":{
                          "width":90,
                          "height":60},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/role/1_u13.png"}},
{
                  "id":"f6ac4186ae384ed38576fc14c6aaa965",
                  "label":"2",
                  "parentDynamicPanel":"54677eb7ef5446178a43cee0eee99a9a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF0000},
                    "location":{
                      "x":595,
                      "y":134},
                    "size":{
                      "width":90,
                      "height":60},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3c3a58a61ba247408efd44e7e63f1c4b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"54677eb7ef5446178a43cee0eee99a9a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF0000},
                        "location":{
                          "x":595,
                          "y":134},
                        "size":{
                          "width":90,
                          "height":60},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/role/1_u13.png"}},
{
                  "id":"d5f5b449549f4a70bdf42d58234b8813",
                  "label":"3",
                  "parentDynamicPanel":"54677eb7ef5446178a43cee0eee99a9a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF0000},
                    "location":{
                      "x":1020,
                      "y":134},
                    "size":{
                      "width":90,
                      "height":60},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"df0245da9b4f445eb150466e746e6b53",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"54677eb7ef5446178a43cee0eee99a9a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF0000},
                        "location":{
                          "x":1020,
                          "y":134},
                        "size":{
                          "width":90,
                          "height":60},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/role/1_u13.png"}},
{
                  "id":"769c4e1c1e1e4c8d85c50550646c4751",
                  "label":"",
                  "parentDynamicPanel":"54677eb7ef5446178a43cee0eee99a9a",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":576,
                      "y":77},
                    "size":{
                      "width":129,
                      "height":37}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"282b7f7c09314901936ef566c3d4b2ef",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"54677eb7ef5446178a43cee0eee99a9a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":576,
                          "y":77},
                        "size":{
                          "width":129,
                          "height":37}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"877c08924a2a409aaf058ee599e0eee1",
                  "label":"开始",
                  "parentDynamicPanel":"54677eb7ef5446178a43cee0eee99a9a",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":1160,
                      "y":640},
                    "size":{
                      "width":100,
                      "height":55}},
                  "adaptiveStyles":{
}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "af3e1c0287e84689b3e15ccca0b0185f":{
      "scriptId":"u0"},
    "8d64ba295096424b91373f6394500e6a":{
      "scriptId":"u1"},
    "54677eb7ef5446178a43cee0eee99a9a":{
      "scriptId":"u2"},
    "fc6f5243773d413b9c002cff7f54ab45":{
      "scriptId":"u3"},
    "2474c754222b44708e3e2b9cce9e1cee":{
      "scriptId":"u4"},
    "bb00d3f4c2304ca499de04ace47df153":{
      "scriptId":"u5"},
    "2ad926228d5d48aa8d25154174e8e7ee":{
      "scriptId":"u6"},
    "2df597973c464c6da9bef5db8efc0e84":{
      "scriptId":"u7"},
    "62d97edc2b194e98ac5ec95ea1691fa2":{
      "scriptId":"u8"},
    "d6f13649c6ec4f9b9c2c4a1f7ac2fcc9":{
      "scriptId":"u9"},
    "1bfd3fec9d3b49eca40c6a45caad8cd7":{
      "scriptId":"u10"},
    "5c2059500b3f4e8988cfe3a83ea39801":{
      "scriptId":"u11"},
    "e515a9eb6c2444e28cf78d43c346a34c":{
      "scriptId":"u12"},
    "d81425072d8f4db885030b7e8e5c5b19":{
      "scriptId":"u13"},
    "0abdbb01083645ef8f9a407a4a334925":{
      "scriptId":"u14"},
    "f6ac4186ae384ed38576fc14c6aaa965":{
      "scriptId":"u15"},
    "3c3a58a61ba247408efd44e7e63f1c4b":{
      "scriptId":"u16"},
    "d5f5b449549f4a70bdf42d58234b8813":{
      "scriptId":"u17"},
    "df0245da9b4f445eb150466e746e6b53":{
      "scriptId":"u18"},
    "769c4e1c1e1e4c8d85c50550646c4751":{
      "scriptId":"u19"},
    "282b7f7c09314901936ef566c3d4b2ef":{
      "scriptId":"u20"},
    "877c08924a2a409aaf058ee599e0eee1":{
      "scriptId":"u21"}}});